### ISSUE TITLE
is there a way to automate this to get always latest h5bp?

### ISSUE THREAD

**Issue by COLABORATI** [h5bp/generator-h5bp#22]
is there a way to automate this to get always latest h5bp?

**Comment by sindresorhus** [comment]
No, it's dependent on the H5BP file structure, and would break if that changed. I just upgraded to latest version of H5BP. Enjoy ;)

**Comment by COLABORATI** [comment]
thank you very much!

**Comment by steveoh** [comment]
What is your process for keeping this up to date with the H5BP? We are thinking of converting a project, that we often use as a boilerplate but is also a website, into a generator. The idea being the defaults, or a fast path, would create the website. But, if we wanted to start with a boilerplate we could do that also and it would walk through all the options.

I am very curious how to best keep a generator current when dev'ing and testing the output project since it can't be fun to add new features to the output and then port them into the generator.

**Comment by sindresorhus** [comment]
@steveoh As long as you're doing conditional generation, there's no way to do it fully automatically, as the conditionals depend on the source, and the source might change between versions. In this generator I just upgrade when I see a new H5BP release on Twitter or if someone requests it. If you'd want to be more proactive you could subscribe to the H5BP GitHub releases feed.
